GET http://localhost:3042/customers

###

GET http://localhost:3042/customers/1

###

POST http://localhost:3042/customers
Content-Type: application/json

{
    "firstName": "Piet",
    "surName": "Channel",
    "email": "hi@fefe.nl",
    "phoneNumber": "49289035809",
    "homeAddress": "hi",
    "homeCountry": "London"
}

###

DELETE http://localhost:3042/customers/2

###

PATCH  http://localhost:3042/customers/2
Content-Type: application/json

{
    "firstName": "Pieter",
    "surName": "Channel3",
    "email": "hi3@fefe.nl",
    "homeAddress": "hi2"
}