GET http://localhost:3042/customers

###

GET http://localhost:3042/customers/1

###

POST http://localhost:3042/customers
Content-Type: application/json

{
    "firstName": "Piet",
    "surName": "Channel",
    "email": "hi@fefe.nl",
    "phoneNumber": "49289035809",
    "homeAddress": "hi",
    "homeCountry": "London"
}

###

DELETE http://localhost:3042/customers/2

###

PATCH  http://localhost:3042/customers/3
Content-Type: application/json

{
    "firstName": "Pieter",
    "surName": "Channel3",
    "email": "hi3@fefe.nl",
    "homeAddress": "hi2"
}

###

GET http://localhost:3042/bookings

###

GET http://localhost:3042/bookings/1

###

POST http://localhost:3042/bookings
Content-Type: application/json

{
    "customerID": 3,
    "spotID": 1,
    "startDate": "2024-2-12",
    "endDate": "2024-4-14",
    "adults": 2,
    "children": 0,
    "transactionPrice": 5.223
}

###

DELETE http://localhost:3042/bookings/3

###

PATCH  http://localhost:3042/bookings/2
Content-Type: application/json

{
    "customerID": 4
}

###

GET http://localhost:3042/campingspots

###

GET http://localhost:3042/campingspots/1

###

POST http://localhost:3042/campingspots
Content-Type: application/json

{
    "spotName": "Jemoeder",
    "spotSize": "Small",
    "pricePerDay": 2.5
}

###

DELETE http://localhost:3042/campingspots/3

###

PATCH  http://localhost:3042/campingspots/2
Content-Type: application/json

{
    "spotSize": "Big"
}