GET http://localhost:3000/customers

###

GET http://localhost:3000/customers/1

###

POST http://localhost:3000/customers
Content-Type: application/json

{
    "firstName": "Piet",
    "surName": "Channel",
    "email": "hi@fefe.nl",
    "phoneNumber": "49289035809",
    "homeAddress": "hi",
    "homeCountry": "London"
}

###

DELETE http://localhost:3000/customers/

###

PATCH  http://localhost:3000/customers/

{
    "firstName": "Pieter",
    "surName": "Channel2",
    "email": "hi@fefe.nl",
    "phoneNumber": "49289035809",
    "homeAddress": "hi2",
    "homeCountry": "London"
}